
ROOTDIR         := {{ROOTDIR}}
EXECUTABLE      := runner
SOURCES         := runner.cu

INCLUDE_FLAGS   := 
LINK_FLAGS      := 
CCFLAGS         := 
NVCCFLAGS       := 

ifdef COMSPEC
        include $(GeNNPATH)/lib/include/makefile_common_cygwin.mk
else
        include $(GeNNPATH)/lib/include/makefile_common.mk
endif
