version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3"  # latest stable CPython
  jobs:
    post_install:
        - python -m pip install .
        - python -m pip install sphinxcontrib-issuetracker
